bind = "127.0.0.1:5000"
welcome_message = "Welcome to PicoLimbo!"
action_bar = "Welcome to PicoLimbo!"
default_game_mode = "spectator"
hardcore = false
fetch_player_skins = false

[forwarding]
method = "NONE"

[world]
spawn_position = [
    0.0,
    320.0,
    0.0,
]
dimension = "end"
time = "day"

[world.experimental]
view_distance = 2
schematic_file = ""
lock_time = false

[world.boundaries]
enabled = true
min_y = -64
teleport_message = "<red>You have reached the bottom of the world.</red>"

[server_list]
max_players = 20
message_of_the_day = "A Minecraft Server"
show_online_player_count = true
server_icon = "server-icon.png"

[compression]
threshold = -1
level = 6

[tab_list]
enabled = true
header = "<bold>Welcome to PicoLimbo</bold>"
footer = "<green>Enjoy your stay!</green>"

[boss_bar]
enabled = false
title = "<bold>Welcome to PicoLimbo!</bold>"
health = 1.0
color = "pink"
division = 0

[title]
enabled = false
title = "<bold>Welcome!</bold>"
subtitle = "Enjoy your stay"
fade_in = 10
stay = 70
fade_out = 20
